AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - 'legion-mcp.gemspec'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/PredicateMethod:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
