AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - 'legion-mcp.gemspec'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/PredicateMethod:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ModuleLength:
  Max: 250

Layout/LineLength:
  Max: 140
