# frozen_string_literal: true

# Requires all built-in MCP tool files so they are defined as Ruby constants.
# server.rb no longer owns these requires — Legion::Tools::Registry provides
# runtime registration, but the classes must still be defined for specs and
# for any code that references Legion::MCP::Tools::* directly.

require_relative 'tools/run_task'
require_relative 'tools/describe_runner'
require_relative 'tools/list_tasks'
require_relative 'tools/get_task'
require_relative 'tools/delete_task'
require_relative 'tools/get_task_logs'
require_relative 'tools/list_chains'
require_relative 'tools/create_chain'
require_relative 'tools/update_chain'
require_relative 'tools/delete_chain'
require_relative 'tools/list_relationships'
require_relative 'tools/create_relationship'
require_relative 'tools/update_relationship'
require_relative 'tools/delete_relationship'
require_relative 'tools/list_extensions'
require_relative 'tools/get_extension'
require_relative 'tools/enable_extension'
require_relative 'tools/disable_extension'
require_relative 'tools/list_schedules'
require_relative 'tools/create_schedule'
require_relative 'tools/update_schedule'
require_relative 'tools/delete_schedule'
require_relative 'tools/get_status'
require_relative 'tools/get_config'
require_relative 'tools/list_workers'
require_relative 'tools/show_worker'
require_relative 'tools/worker_lifecycle'
require_relative 'tools/worker_costs'
require_relative 'tools/team_summary'
require_relative 'tools/routing_stats'
require_relative 'tools/rbac_check'
require_relative 'tools/rbac_assignments'
require_relative 'tools/rbac_grants'
require_relative 'tools/prompt_list'
require_relative 'tools/prompt_show'
require_relative 'tools/prompt_run'
require_relative 'tools/dataset_list'
require_relative 'tools/dataset_show'
require_relative 'tools/experiment_results'
require_relative 'tools/eval_list'
require_relative 'tools/eval_run'
require_relative 'tools/eval_results'
require_relative 'tools/do_action'
require_relative 'tools/plan_action'
require_relative 'tools/discover_tools'
require_relative 'tools/ask_peer'
require_relative 'tools/list_peers'
require_relative 'tools/notify_peer'
require_relative 'tools/broadcast_peers'
require_relative 'tools/mesh_status'
require_relative 'tools/mind_growth_status'
require_relative 'tools/mind_growth_propose'
require_relative 'tools/mind_growth_approve'
require_relative 'tools/mind_growth_build_queue'
require_relative 'tools/mind_growth_cognitive_profile'
require_relative 'tools/mind_growth_health'
require_relative 'tools/query_knowledge'
require_relative 'tools/knowledge_health'
require_relative 'tools/knowledge_context'
require_relative 'tools/absorb'
require_relative 'tools/structural_index'
require_relative 'tools/tool_audit'
require_relative 'tools/state_diff'
require_relative 'tools/search_sessions'
require_relative 'tools/skills'
